<?xml version="1.0"?>
<package format="2">
  <name>slda_bci</name>
  <version>0.0.0</version>
  <description>The slda_bci package</description>

  <maintainer email="paolo@todo.todo">paolo</maintainer>

  <license>TODO</license>

  <buildtool_depend>catkin</buildtool_depend>
  <build_depend>roscpp</build_depend>
  <build_depend>rospy</build_depend>
  <build_depend>std_msgs</build_depend>
  <build_depend>processing_bci</build_depend>
  <build_depend>rosneuro_msgs</build_depend>
  <build_export_depend>rospy</build_export_depend>
  <build_export_depend>std_msgs</build_export_depend>
  <build_export_depend>processing_bci</build_export_depend>
  <build_export_depend>rosneuro_msgs</build_export_depend>
  <exec_depend>roscpp</exec_depend>
  <exec_depend>rospy</exec_depend>
  <exec_depend>std_msgs</exec_depend>
  <exec_depend>processing_bci</exec_depend>
  <exec_depend>rosneuro_msgs</exec_depend>

</package>
