#!/usr/bin/env python3

import pickle
import rospy
from processing_bci.msg import eeg_fbcsp
from rosneuro_msgs.msg import NeuroOutput, NeuroEvent
import numpy as np

class Slda:
    def __init__(self):
        rospy.init_node('slda', anonymous=True)
        self.slda_name = "slda_model"
        
        try:
            self.path_decoder = rospy.get_param('~path_slda_model')
        except KeyError as e:
            rospy.logfatal(f"[{self.slda_name}] Mandatory parameter: 'path_slda_model'. Error:{e}.")
            return
            
        topic_sub = rospy.get_param('~topic_sub', '/eeg_fbcsp')
        
        try:
            self.slda_paradigm = rospy.get_param('~slda_paradigm')
        except KeyError as e:
            rospy.logfatal(f"[{self.slda_name}] Mandatory parameter: 'slda_paradigm'. Error:{e}.")
            return
        self.slda_name += f"_{self.slda_paradigm}"
        
        conf = self.configure()
        if not conf:
            rospy.logfatal(f"[{self.slda_name}] Error in the sLDA configuration.")
            return
        else:
            rospy.loginfo(f"[{self.slda_name}] sLDA configurated correctly.")

        self.baseline = 0.0
        self.is_baseline_recording = False
        self.baseline_buffer = []

        rospy.Subscriber(topic_sub, eeg_fbcsp, self.callback)
        rospy.Subscriber('/events/bus', NeuroEvent, self.on_event)
        self.pub = rospy.Publisher(f'/{self.slda_paradigm}/neuroprediction/raw', NeuroOutput, queue_size=10)
        
        rospy.spin()
        
    def configure(self):
        try:
            with open(self.path_decoder, 'rb') as file:
                save_dict = pickle.load(file)
        except Exception as e:
            rospy.logerr(f"[{self.slda_name}] Error loading sLDA pickle file: {e}")
            return False
            
        try:
            self.clf = save_dict['model']
            self.classes_ = np.array(save_dict['classes'])
            self.nclasses = len(self.classes_)
            self.nfeatures = len(save_dict['bands']) * len(save_dict['selected_components_indices'])
        except Exception as e:
            rospy.logerr(f"[{self.slda_name}] Error parsing the sLDA's parameter: {e}")
            return False

        return True
        
    def extract_features(self, msg):
        data = msg.data
        
        # In FBCSP, the message data contains flattened [components x bands] in column-major.
        # This matches exactly the concatenated [band1_comp1, band1_comp2, ..., band2_comp1, ...] used in training
        # as long as the Fbcsp c++ node uses the same CSP YAML file generated by the notebook.
        if len(data) != self.nfeatures:
            rospy.logwarn_throttle(1.0, f"[{self.slda_name}] Expected {self.nfeatures} features, got {len(data)}. Ensure FBCSP node uses the correct csp.yaml.")
            return None
            
        return data
        
    def on_event(self, msg):
        if msg.event == 786:
            self.is_baseline_recording = True
            self.baseline_buffer = []
            rospy.loginfo(f"[{self.slda_name}] Started baseline recording.")
        elif hasattr(self, 'classes_') and msg.event in self.classes_.astype(int):
            if self.is_baseline_recording:
                self.is_baseline_recording = False
                if len(self.baseline_buffer) > 0:
                    mean_val = np.mean(self.baseline_buffer, axis=0)
                    self.baseline = np.log(mean_val)
                    rospy.loginfo(f"[{self.slda_name}] Baseline computed.")
                else:
                    rospy.logwarn(f"[{self.slda_name}] No FBCSP data received during baseline recording! Baseline remains {self.baseline}")

    def callback(self, msg):
        raw_dfet = self.extract_features(msg)
        if raw_dfet is None:
            return
            
        if self.is_baseline_recording:
            self.baseline_buffer.append(raw_dfet)
            
        # The FBCSP node publishes variance. We need log-variance for our trained sLDA.
        dfet = np.log(raw_dfet) - self.baseline
        
        dfet = np.array(dfet).reshape(1, -1)
        probabilities = self.clf.predict_proba(dfet)[0]
        
        hard_pred_vector = np.zeros(self.nclasses, dtype=int)
        hard_pred_vector[np.argmax(probabilities)] = 1
        
        output = NeuroOutput()
        output.header.stamp = rospy.Time.now()
        output.neuroheader.seq = msg.seq
        output.softpredict.data = probabilities.tolist()
        output.hardpredict.data = hard_pred_vector.tolist() 
        output.decoder.type = self.slda_name
        output.decoder.path = self.path_decoder
        output.decoder.classes = self.classes_.astype(int).tolist()
        self.pub.publish(output)

if __name__ == '__main__':
    Slda()
